[package]
name = "vroom"
version = "0.1.0"
edition = "2024"

[dependencies]
linux-embedded-hal = "0.4.0"
pca9685 = "0.1.0"
pwm-pca9685 = "1.0.0"
rppal = "0.22.1"
socketcan = "3.5.0"

# [[bin]]
# name = "vroom_can"
# path = "src/main2.rs"
